spring.application.name=parkingslot

server.servlet.context-path=/parkingslot
server.port=8080
server.address=0.0.0.0

# PostgreSQL Configuration (Render DB)
spring.datasource.url=jdbc:postgresql://ep-noisy-cell-adc0uxox-pooler.c-2.us-east-1.aws.neon.tech/parkingSlot?user=neondb_owner&password=npg_JRZ19yESzHrd&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_JRZ19yESzHrd

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Logging
spring.main.banner-mode=off
